sudo: required
services:
  - docker
addons:
  postgresql: "9.5"
language: python
python:
  - 3.6
env:
  - SECRET_KEY="TRAVIS-SECRET-KEY"
install:
  - pip install -r backend/requirements/dev.txt

  - nvm install 8.12.0
  - cd frontend && npm install && cd -
before_script:
  - psql -c "CREATE USER \"pah-fm\" WITH PASSWORD 'pah-fm';" -U postgres
  - psql -c "ALTER USER \"pah-fm\" CREATEDB;" -U postgres
script:
  - cd backend
  - flake8 backend --config=backend/.flake8
  - python manage.py test
  - cd ..

  - cd frontend
  - npm run lint
  - cd ..
after_success:
  - |
    if [ "$TRAVIS_REPO_SLUG" == "CodeForPoznan/pah-fm" ] &&
       [ "$TRAVIS_BRANCH" == "develop" ] &&
       [ "$TRAVIS_PULL_REQUEST" = false ];
    then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      cd backend;
      docker build -f Dockerfile -t codeforpoznan/pah-fm-backend:latest .;
      docker push codeforpoznan/pah-fm-backend;
      cd ../frontend;
      docker build -f Dockerfile -t codeforpoznan/pah-fm-frontend:latest .;
      docker push codeforpoznan/pah-fm-frontend;
      cd ..;
    fi
