version:  ~> 1.0
os:       linux
dist:     bionic
language: python
python:   ["3.6"]
services: docker
addons:
  postgresql: "9.5"
cache:
  pip: true
  directories:
    - "$HOME/.npm"

env:
  global:
    - SECRET_KEY=TRAVIS-SECRET-KEY
    - secure: "FvksvizyP/p/ZmMD+Dq5STciE5EXAtPFMG4GI84QbQ7jcAFyIqSqxHAfhBpC4mW0Mu3Tv8Iz8/K24bcAL3AwKINKD3L+G7qing+y+/5XzGNudLMFNt9Ag+bm3o3KkbSVSGmH1zWccuE2SpFwFYT7MpBsvXIoYyeuesPpoUtr0SopYvBKXPOCxqNrC27tVWsND1AyM7T0+xmLye4S6s4cuDcIuzUw9XhIUK4tZdEPZkKODwjQ8aAIOHDWs0B8xiqe7+z4UlW6wewsVk9ZV5ij7RVuBcBUmLJn/RaT87TZ1fRE/s7eNP8sQGfFuU1gTYMw7Nj+/8kA8JjSegxhudaxZAVH6kQ321mEPGVhoZOhLV5/shBXYT39eI2vXtYigmXRz6RLZSvKjA/ZKRuYRxrg4KvdL1sdxcHgrznZN4UxkwdL4RZYUOgb0Hko/3ZLS4qOcPlEEF1LtZa3gqhmmgUQP0Z9qdVSemQYt2K9QFMF75Yy5mx/rRnEwVBOrlIsKZmULphOVakMSKzLlhatx28dFyO7wpMBbt2yzAX3Uw1UVzoI3v2WcDmdXjYwTSaCkpU8iBx5TA7NvkGG538L35ZI/TH04Osu33JYg/hIyVE/GjiD4vEmJo6Qcr/1pSE38stGVNDTqN6beOUUIgAQ9mBV4vDXwWvE8oVUE9I4qJYWKWU="

    # TRANSIFEX_SECRET=...
    - secure: "gqJnvEb14KilGilinFpzIq0/mPGwOCrs0EsgcSzTN8q/D725ETCaT24+4npTNGw30zk7RGTf/6SWdh9S1vKFMpTQbHE0oG88nES49T5IZV4HPS6yxgq4tnhf6XDq5Q9fHwxjOsEnsA7fDdPRLAahiPdBbIZAabHO0i6isdvWYgbpkRSA1VE/ZBwpFy2hNFRVR3vW+2GWk0n4RdVrgWy164RRzJUXcEaq/oOlXZU8F9lKPDHnfkpCw1YXsLZqNf2CcG4WKYTJomGTu8Gq3a5hmHM25dI8fiJWbrsDRwkE6asMYxz4kHHLPINfUElhu2zU2BUDlLCuM+yWFV4ZPDSFEErW+CfH5j8p1Y3FzCqJt2aL5WkqhlpE7Jsu2R1s80ug8HlddE5Ct0VPG2B2TPGSXwCaPcIszWLTppq1XjhJAYgesMT3PEwKaeSlXYBqL5OyG8ubdo4t7tLkRdQomzaEn5G9HfjZ9/QW15o0PSI/P6geEg25ls5mT317NzG+ummw3jw03bRzZak7h+j2RROySoj4JfzpmDGZNoNM1QE8zbDfzefVVzpsq7f4qG8LIqFNiEMi5QDFcmgbiqqx76FO4sw59dJratCDHBeGJvNamStbGFpCfvCQaD3UXqUMx5+NW8+aegovk+3R61+DdI8alL9k4YQ5OHuCiFAycULhQas="
    - TRANSIFEX_TOKEN=1/0295575608a243c1442a518c21751c8d6b1f2c53


install:
  # install languages
  - nvm install 8.12.0

  # install dependencies
  - (cd frontend && npm ci)
  - (cd backend  && pip install -r requirements/dev.txt)

  # prepare database
  - psql -U postgres -c "CREATE USER \"pah-fm\" WITH PASSWORD 'pah-fm';"
  - psql -U postgres -c "ALTER  USER \"pah-fm\" CREATEDB;"


script:
  # lint and test frontend
  - (cd frontend && npm run lint)
  - (cd frontend && npm run test)

  # lint and test backend
  - (cd backend  && flake8 .)
  - (cd backend  && black --check .)
  - (cd backend  && python manage.py test)


deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    repo: CodeForPoznan/pah-fm
    branch: master
