version: ~> 1.0  # for imports


language: python
python:   ["3.6"]

addons:
  postgresql: "9.5"

env:
  global:
    - SECRET_KEY=TRAVIS-SECRET-KEY


install:
  # install dependencies
  - (cd frontend && npm install --quiet)
  - (cd backend  && pip install --quiet -r requirements/dev.txt)

  # prepare database
  - psql -U postgres -c "CREATE USER \"pah-fm\" WITH PASSWORD 'pah-fm';"
  - psql -U postgres -c "ALTER  USER \"pah-fm\" CREATEDB;"


script:
  # lint and test frontend
  - (cd frontend && npm run lint)
  - (cd frontend && npm run test)

  # lint and test backend
  - (cd backend  && flake8 .)
  - (cd backend  && python manage.py test)


import:
  # deploy on merge
  - source: .deploy.yml
    mode: deep_merge_append
#   if: branch = master and
#       type   = push   and
#       repo   = 'CodeForPoznan/pah-fm'
