version: ~> 1.0


language: python
python:   ["3.6"]

addons:
  postgresql: "9.5"

env:
  global:
    - SECRET_KEY="TRAVIS-SECRET-KEY"
    - secure: "FvksvizyP/p/ZmMD+Dq5STciE5EXAtPFMG4GI84QbQ7jcAFyIqSqxHAfhBpC4mW0Mu3Tv8Iz8/K24bcAL3AwKINKD3L+G7qing+y+/5XzGNudLMFNt9Ag+bm3o3KkbSVSGmH1zWccuE2SpFwFYT7MpBsvXIoYyeuesPpoUtr0SopYvBKXPOCxqNrC27tVWsND1AyM7T0+xmLye4S6s4cuDcIuzUw9XhIUK4tZdEPZkKODwjQ8aAIOHDWs0B8xiqe7+z4UlW6wewsVk9ZV5ij7RVuBcBUmLJn/RaT87TZ1fRE/s7eNP8sQGfFuU1gTYMw7Nj+/8kA8JjSegxhudaxZAVH6kQ321mEPGVhoZOhLV5/shBXYT39eI2vXtYigmXRz6RLZSvKjA/ZKRuYRxrg4KvdL1sdxcHgrznZN4UxkwdL4RZYUOgb0Hko/3ZLS4qOcPlEEF1LtZa3gqhmmgUQP0Z9qdVSemQYt2K9QFMF75Yy5mx/rRnEwVBOrlIsKZmULphOVakMSKzLlhatx28dFyO7wpMBbt2yzAX3Uw1UVzoI3v2WcDmdXjYwTSaCkpU8iBx5TA7NvkGG538L35ZI/TH04Osu33JYg/hIyVE/GjiD4vEmJo6Qcr/1pSE38stGVNDTqN6beOUUIgAQ9mBV4vDXwWvE8oVUE9I4qJYWKWU="


install:
  # install dependencies
  - (cd frontend && npm install --quiet)
  - (cd backend  && pip install --quiet -r requirements/dev.txt)

  # prepare database
  - psql -U postgres -c "CREATE USER \"pah-fm\" WITH PASSWORD 'pah-fm';"
  - psql -U postgres -c "ALTER  USER \"pah-fm\" CREATEDB;"


script:
  # lint and test frontend
  - (cd frontend && npm run lint)
  - (cd frontend && npm run test)

  # lint and test backend
  - (cd backend  && flake8 .)
  - (cd backend  && python manage.py test)


import:
  # deploy on merge
  - source: .deploy.yml
    mode: deep_merge_append
#   if: branch = master and
#       type   = push   and
#       repo   = 'CodeForPoznan/pah-fm'
