# Generated by Django 2.1.2 on 2018-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='fuel_level_begin',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fuel_level_end',
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='route',
            name='place_destination',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='route',
            name='place_from',
            field=models.CharField(default='', max_length=50),
        ),
    ]
