# Generated by Django 2.1.2 on 2018-12-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0004_auto_20181129_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
