# Generated by Django 2.1.2 on 2019-03-06 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0006_verificationtoken"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="drives",),
        migrations.AddField(
            model_name="drive",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="fleet_management.Project",
            ),
            preserve_default=False,
        ),
    ]
