# Generated by Django 2.1.2 on 2019-03-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0006_verificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='drives',
        ),
        migrations.AddField(
            model_name='drive',
            name='project',
            field=models.ManyToManyField(to='fleet_management.Project'),
        ),
    ]
