# Generated by Django 2.1.2 on 2019-03-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0007_auto_20190306_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='project',
        ),
        migrations.AddField(
            model_name='drive',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet_management.Project'),
            preserve_default=False,
        ),
    ]
