# Generated by Django 2.1.2 on 2019-07-27 20:12
import random

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0008_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='timestamp',
            field=models.IntegerField(default=random.randint(1, 999999999)),
        ),
    ]
