# Generated by Django 2.1.2 on 2019-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet_management", "0011_add_default_groups"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="mileage_unit",),
    ]
