# Generated by Django 2.1.2 on 2019-08-26 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


passengers = []


def create_users_from_passengers():
    # todo: convert passengers to users
    # todo: create hash map of which drive user belonged to
    # todo: provide passwords
    True


def insert_users_to_drives():
    # todo: insert users to drives
    True


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0014_auto_20190821_1926'),
    ]

    operations = [
        migrations.RunPython(create_users_from_passengers),
        migrations.RemoveField(
            model_name='drive',
            name='passengers',
        ),
        migrations.AddField(
            model_name='drive',
            name='passengers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_passengers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.RunPython(insert_users_to_drives),

    ]
