# Generated by Django 2.1.2 on 2019-10-11 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0016_auto_20190825_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rsa_modulus_n',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AddField(
            model_name='user',
            name='rsa_priv_d',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AddField(
            model_name='user',
            name='rsa_pub_e',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
