# Generated by Django 2.1.2 on 2019-10-02 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0016_auto_20190825_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drives_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drive',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives_driven', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2),
        ),
    ]
