# Generated by Django 2.1.2 on 2019-10-02 19:00

from django.db import migrations


def migrate_passenger_to_user(apps, schema_editor):
    Passenger = apps.get_model("fleet_management", "Passenger")
    User = apps.get_model("fleet_management", "User")
    Group = apps.get_model("auth", "Group")
    Drive = apps.get_model("fleet_management", "Drive")
    g = Group.objects.get(name="Passenger")
    passengers = Passenger.objects.all()
    for p in passengers:
        u = User.objects.create(
            username=f"pass_{p.id}@pah.org.pl",
            email=p.email,
            is_superuser=False,
            is_staff=False,
            country=p.country,
            is_active=True,
            first_name=p.first_name,
            last_name=p.last_name
        )
        u.save()
        g.user_set.add(u)

        drives = Drive.objects.filter(passengers=p.id)
        for d in drives:
            assert d.passengers.all().count() == 1, f"Too many passengers in a drive {d.id}"
            d.passenger = u
            d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0017_auto_20191002_1858'),
    ]

    operations = [
        migrations.RunPython(migrate_passenger_to_user),
    ]
