# Generated by Django 2.2.10 on 2020-03-12 15:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0022_auto_20191221_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
