name: test backend

on:
  workflow_call:
  pull_request:
    branches: [master]
    paths: ['backend/**']

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - uses: CodeForPoznan/actions/setup-backend@main
      - uses: CodeForPoznan/actions/lint-backend@main

      - run: pipenv run pytest

      - uses: CodeForPoznan/actions/pack-backend@main
        if: github.event_name != 'pull_request'
